### ISSUE TITLE
django 3.1 won't work

### ISSUE THREAD

**Issue by g4ndy** [lino-framework/getlino#2]
django 3.1 and newer will break the installation of lino because lino depends on compatibility import of django.core.exceptions.FieldDoesNotExist in django.db.models.fields which is removed from django 3.1 so i suggest to require django==3.0.9 somewhere explicitly

**Comment by lsaffre** [comment]
Yes, I just discovered this as well. Working on it. There will soon be a new version of the relevant Lino packages, so we don't need to adapt getlino.

**Comment by lsaffre** [comment]
(oops, this issue has been fixed long time ago... just forgot to close it here)
